### PR TITLE
Update AppHost nuget package

### PR DESCRIPTION
**Pull request by jameswrightrg**

### CODE REVIEW

**Comment by jameswrightrg** [comment]
Don't merge - doesn't build yet

**Comment by david-connell** [comment]
OK well there were a load of probs on the build system.
This is now fixed I think so this may work. I have fixed the problems by hacking the nuget package
so it;s less invasive and I don't believe that it needs too much testing...

**Comment by david-connell** [comment]
So I'll let you decide what you want to do with this branch

**Comment by jameswrightrg** [comment]
I think this branch is now redundant

**Pull request closed without merging**
